version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEB_TAG=v1.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro